[package]
name = "http_chunked"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
httpdate = "1.0.3"
tokio = { version = "1.34.0", features = [
    "rt-multi-thread",
    "macros",
    "time",
    "net",
    "fs",
    "io-util",
] }
